"""baseline: the schema production already has

Revision ID: 0001_baseline
Revises:
Create Date: 2026-08-31 21:58:29.108640+00:00

THIS MIGRATION MUST NOT RUN AGAINST PRODUCTION. STAMP IT INSTEAD.
=================================================================

Alembic is being adopted onto a database that already exists and is full:
5 populated tables, 49 columns, 4 enum types, and 3.8 TB of mirror state behind
them. The live schema was built by `Base.metadata.create_all`, which is now
removed -- see backend/app/core/database.py.

`upgrade()` below is what `create_all` would emit today, autogenerated against
an empty database from shared/models/ and left byte-for-byte as Alembic wrote
it. Running it on the live database would attempt CREATE TABLE over live data
and fail on the first statement. The point of this revision is not to be run
there; it is to be the revision the live database is DECLARED to already be at:

    docker compose run --rm --no-deps --entrypoint alembic backend -c /app/alembic.ini stamp 0001_baseline

or, equivalently and preferably, the wrapper that checks first:

    scripts/migrate.sh adopt

`stamp` writes one row into alembic_version and executes no DDL. After it, the
first real `alembic upgrade head` is a no-op, and `alembic check` reports no
difference between shared/models/ and the live schema. That empty diff is the
proof the baseline is correct; if it is not empty, this file is wrong and must
be fixed before anything else is applied.

On a FRESH database -- `setup.sh --clean`, a dev laptop, CI -- `upgrade()` is
the thing that builds the schema, and it is the only thing that does. There is
no second mechanism any more.

WHAT IS PINNED HERE THAT IS EASY TO LOSE
----------------------------------------
  * Enum LABELS AND THEIR ORDER. Every enum is stored by member NAME, not
    value: mirror_status is ('ACTIVE','SYNCING','ERROR','DISABLED') in that
    order, because SQLAlchemy's Enum(PyEnum) uses the names. Order is part of
    the Postgres type and cannot be altered without recreating it.
  * sync_jobs.triggered_by carries a COLUMN COMMENT. It exists in production.
  * ON DELETE CASCADE on sync_jobs.mirror_id, ON DELETE SET NULL on
    audit_logs.user_id.
  * settings.key and users.username are UNIQUE INDEXES (ix_*); mirrors.name and
    users.email are UNIQUE CONSTRAINTS. That asymmetry is what production has.

REVIEW CHECKLIST
  [x] Runs against tables with rows in them?  NO -- it must never run there.
      It is stamped on the existing database and applied only to empty ones.
  [x] Long lock?  Not applicable for the same reason.
  [x] Safe for the currently running code?  Yes: on production it executes
      nothing at all.
  [x] downgrade() loses data?  It would drop all five tables, so it refuses.
      See the body below.
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '0001_baseline'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mirrors',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('mirror_type', sa.Enum('FREEBSD', 'NETBSD', 'OPENBSD', name='mirror_type'), nullable=False),
    sa.Column('upstream_url', sa.String(length=500), nullable=False),
    sa.Column('local_path', sa.String(length=500), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'SYNCING', 'ERROR', 'DISABLED', name='mirror_status'), nullable=False),
    sa.Column('last_sync_started', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_sync_completed', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_sync_error', sa.Text(), nullable=True),
    sa.Column('total_size_bytes', sa.BigInteger(), nullable=True),
    sa.Column('file_count', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('settings',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('key', sa.String(length=100), nullable=False),
    sa.Column('value', sa.Text(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_settings_key'), 'settings', ['key'], unique=True)
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('ADMIN', 'OPERATOR', 'READONLY', name='user_role'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_login', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('audit_logs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('resource_type', sa.String(length=50), nullable=False),
    sa.Column('resource_id', sa.String(length=100), nullable=True),
    sa.Column('details', sa.JSON(), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_logs_action'), 'audit_logs', ['action'], unique=False)
    op.create_index(op.f('ix_audit_logs_created_at'), 'audit_logs', ['created_at'], unique=False)
    op.create_index(op.f('ix_audit_logs_user_id'), 'audit_logs', ['user_id'], unique=False)
    op.create_table('sync_jobs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('mirror_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'RUNNING', 'COMPLETED', 'FAILED', 'CANCELLED', name='sync_status'), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('files_transferred', sa.BigInteger(), nullable=True),
    sa.Column('bytes_transferred', sa.BigInteger(), nullable=True),
    sa.Column('files_deleted', sa.BigInteger(), nullable=True),
    sa.Column('rsync_output', sa.Text(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('triggered_by', sa.String(length=50), nullable=True, comment='scheduled, manual, or username'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['mirror_id'], ['mirrors.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sync_jobs_mirror_id'), 'sync_jobs', ['mirror_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Refuses. Downgrading past the baseline means dropping the database.

    Alembic would happily generate `op.drop_table` for all five tables here,
    and `alembic downgrade base` is four keystrokes from `alembic downgrade
    head`. On this deployment those tables hold the mirror inventory, every
    sync job's history, the settings the scheduler reads and the admin users --
    the metadata for 3.8 TB of files that would then have nothing describing
    them.

    There is no reversible sense in which a database is "downgraded below its
    own creation", so this is not a missing feature. If a fresh install really
    needs to start over, destroy the database rather than migrate it:

        docker compose down -v          # removes the postgres-data volume
        scripts/setup.sh --mode dev --clean

    Every LATER revision must implement a real downgrade(); the deploy path
    depends on it. This one, and only this one, is a wall.
    """
    raise NotImplementedError(
        "downgrade past 0001_baseline would DROP all five tables. "
        "This baseline is stamped onto an existing database, never unapplied "
        "from one. To destroy a development database instead, use "
        "`docker compose down -v`."
    )
